# -*- coding: utf-8 -*-
"""hand seg with yolo v11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m8C6SeGlmEc4xAK-g4lVI5e2ZoOGpgiw

mount google drive
"""

from google.colab import drive
drive.mount('/content/drive')

# Install the latest stable Ultralytics which includes YOLO11
!pip install -q ultralytics

from ultralytics import YOLO
print("Ultralytics imported OK")

import os
from pathlib import Path

# Where your Project 4 dataset folder is on Google Drive
DATASET_DIR = "/content/drive/MyDrive/hs_yolo_11"

# Go into that folder
os.chdir(DATASET_DIR)
print("We are now in:", os.getcwd())

# Create the YAML file
# We use the same folder for train and val since you have no split
yaml_text = f"""
path: {DATASET_DIR}
train: images
val: images

nc: 2
names: ['Hand', 'Gel']
"""

with open("hs_yolo_11.yaml", "w") as f:
    f.write(yaml_text)

yaml_path = str(Path("hs_yolo_11.yaml").resolve())

print("YAML created successfully")
print("Contents:", yaml_text)

from ultralytics import YOLO

# Load YOLO11 nano model
# Colab will download it automatically
model = YOLO("yolo11n.pt")

print("YOLO11 model loaded successfully")

import torch

results = model.train(
    task="detect",
    data=yaml_path,
    epochs=50,
    imgsz=640,
    batch=4,
    device="0" if torch.cuda.is_available() else "cpu",
    project="hs_yolo11_runs",
    name="yolo11n_detect"
)

print("Training finished!")

from pathlib import Path
from google.colab import files

# Find the best weights
best_weights = Path("/content/drive/MyDrive/hs_yolo_11/runs/detect/hs_yolo11_runs/yolo11n_detect/weights/best.pt")

print("File exists?", best_weights.exists())
print("File size:", round(best_weights.stat().st_size / 1024 / 1024, 2), "MB")

# Download to your laptop
files.download(str(best_weights))