# -*- coding: utf-8 -*-
"""yolov11_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTBCpPgu6q9YZF1-Mcf-ZjMKS47oiC_v
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/hand_hygeine_project

!pip install -U ultralytics

import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())

yaml_text = """
path: /content/drive/MyDrive/hand_hygeine_project/dataset
train: images/train
val: images/train

names:
  0: Gel
  1: Hand
"""

with open("/content/drive/MyDrive/hand_hygeine_project/data.yaml", "w") as f:
    f.write(yaml_text)

print("data.yaml created")

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/hand_hygeine_project/yolov13/ultralytics/cfg/models/11/yolo11-seg.yaml")

model.train(
    data="/content/drive/MyDrive/hand_hygeine_project/data.yaml",
    epochs=200,
    imgsz=640,
    batch=16,
    project="/content/drive/MyDrive/hand_hygeine_project/runs",
    name="hand_hygiene_seg",
    device=0
)

from ultralytics import YOLO

best_model = YOLO("/content/drive/MyDrive/hand_hygeine_project/runs/hand_hygiene_seg/weights/best.pt")

best_model.predict(
    source="/content/drive/MyDrive/hand_hygeine_project/dataset/images/val",
    save=True,
    project="/content/drive/MyDrive/hand_hygeine_project/runs",
    name="val_predictions",
    exist_ok=True,
    conf=0.1
)

best_model.predict(
    source="/content/drive/MyDrive/hand_hygeine_project/dataset/images/train",
    save=True,
    project="/content/drive/MyDrive/hand_hygeine_project/runs",
    name="train_predictions",
    exist_ok=True,
    conf=0.25
)

import os, glob

label_dir = "/content/drive/MyDrive/hand_hygeine_project/dataset/labels/train"
files = glob.glob(os.path.join(label_dir, "*.txt"))[:5]

for f in files:
    print("\nFILE:", os.path.basename(f))
    with open(f, "r") as x:
        print(x.read()[:1000])